FROM ubuntu:20.04

RUN apt-get update -q && apt-get install -qy software-properties-common
RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test \
	&& apt-get install -qy --no-install-recommends \
	python3 python3-pip \
	libegl1 libegl1-mesa-dev libfontconfig1-dev \
	g++-11
	
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /lti_server

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD [ "python3", "./server/infra/app.py"]
